services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app # Mount the local project directory to the container
      - /usr/src/app/node_modules # Prevent node_modules from being overwritten
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true
      - NITRO_PORT=3000 # Optional: If Nuxt needs a specific port variable
    stdin_open: true # Keep the container interactive
    tty: true
    command: npm run dev

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - nuxt
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3